services:

  backend:
    image: hms-backend:latest
    container_name: hms-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: hms-frontend:latest
    container_name: hms-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
